/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.7.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as analytics from "../analytics.js";
import type * as api_issues from "../api/issues.js";
import type * as apiKeys from "../apiKeys.js";
import type * as attachments from "../attachments.js";
import type * as auditLogs from "../auditLogs.js";
import type * as auth from "../auth.js";
import type * as auth_config from "../auth.config.js";
import type * as authWrapper from "../authWrapper.js";
import type * as automationRules from "../automationRules.js";
import type * as availability from "../availability.js";
import type * as bookingPages from "../bookingPages.js";
import type * as bookings from "../bookings.js";
import type * as calendarEvents from "../calendarEvents.js";
import type * as calendarEventsAttendance from "../calendarEventsAttendance.js";
import type * as crons from "../crons.js";
import type * as customFields from "../customFields.js";
import type * as customFunctions from "../customFunctions.js";
import type * as dashboard from "../dashboard.js";
import type * as documents from "../documents.js";
import type * as documents_project_access from "../documents_project_access.js";
import type * as documents_security from "../documents_security.js";
import type * as documentTemplates from "../documentTemplates.js";
import type * as documentVersions from "../documentVersions.js";
import type * as e2e from "../e2e.js";
import type * as email_templates_index from "../email/templates/index.js";
import type * as examples_index from "../examples/index.js";
import type * as export_ from "../export.js";
import type * as files from "../files.js";
import type * as github from "../github.js";
import type * as googleCalendar from "../googleCalendar.js";
import type * as googleOAuth_contract from "../googleOAuth.contract.js";
import type * as hourCompliance from "../hourCompliance.js";
import type * as http from "../http.js";
import type * as internal_ai from "../internal/ai.js";
import type * as invites from "../invites.js";
import type * as issueLinks from "../issueLinks.js";
import type * as issues from "../issues.js";
import type * as issues_counts from "../issues_counts.js";
import type * as issues_date_range from "../issues_date_range.js";
import type * as issues_helpers from "../issues/helpers.js";
import type * as issues_load_more from "../issues_load_more.js";
import type * as issues_mutations from "../issues/mutations.js";
import type * as issues_queries from "../issues/queries.js";
import type * as issues_roadmap from "../issues/roadmap.js";
import type * as issues_roadmap_pagination from "../issues/roadmap_pagination.js";
import type * as issues_selectable from "../issues/selectable.js";
import type * as issues_smart_list from "../issues_smart_list.js";
import type * as issues_soft_delete from "../issues/soft_delete.js";
import type * as labelGroups from "../labelGroups.js";
import type * as labels from "../labels.js";
import type * as lib_apiAuth from "../lib/apiAuth.js";
import type * as lib_batchHelpers from "../lib/batchHelpers.js";
import type * as lib_boundedQueries from "../lib/boundedQueries.js";
import type * as lib_constrainedValidators from "../lib/constrainedValidators.js";
import type * as lib_encryption from "../lib/encryption.js";
import type * as lib_errors from "../lib/errors.js";
import type * as lib_issueHelpers from "../lib/issueHelpers.js";
import type * as lib_logger from "../lib/logger.js";
import type * as lib_migrations from "../lib/migrations.js";
import type * as lib_pagination from "../lib/pagination.js";
import type * as lib_permissions from "../lib/permissions.js";
import type * as lib_queryLimits from "../lib/queryLimits.js";
import type * as lib_rateLimiter from "../lib/rateLimiter.js";
import type * as lib_relationships from "../lib/relationships.js";
import type * as lib_softDeleteHelpers from "../lib/softDeleteHelpers.js";
import type * as lib_ssrf from "../lib/ssrf.js";
import type * as lib_teamAccess from "../lib/teamAccess.js";
import type * as lib_timeUtils from "../lib/timeUtils.js";
import type * as lib_userUtils from "../lib/userUtils.js";
import type * as meetingBot from "../meetingBot.js";
import type * as mocks_issues from "../mocks/issues.js";
import type * as multiTenantIsolation from "../multiTenantIsolation.js";
import type * as notificationPreferences from "../notificationPreferences.js";
import type * as notifications from "../notifications.js";
import type * as oauthHealthCheck from "../oauthHealthCheck.js";
import type * as offlineSync from "../offlineSync.js";
import type * as onboarding from "../onboarding.js";
import type * as organizations from "../organizations.js";
import type * as OTPPasswordReset from "../OTPPasswordReset.js";
import type * as OTPVerification from "../OTPVerification.js";
import type * as presence from "../presence.js";
import type * as projectAccess from "../projectAccess.js";
import type * as projectMembers from "../projectMembers.js";
import type * as projects from "../projects.js";
import type * as projects_security from "../projects_security.js";
import type * as projectTemplates from "../projectTemplates.js";
import type * as prosemirror from "../prosemirror.js";
import type * as pumble from "../pumble.js";
import type * as purge from "../purge.js";
import type * as rateLimiting from "../rateLimiting.js";
import type * as rateLimits from "../rateLimits.js";
import type * as rbac from "../rbac.js";
import type * as reactions from "../reactions.js";
import type * as savedFilters from "../savedFilters.js";
import type * as serviceRotation from "../serviceRotation.js";
import type * as softDeleteCleanup from "../softDeleteCleanup.js";
import type * as sprints from "../sprints.js";
import type * as teams from "../teams.js";
import type * as templates from "../templates.js";
import type * as testConfig from "../testConfig.js";
import type * as testUtils from "../testUtils.js";
import type * as timeTracking from "../timeTracking.js";
import type * as timeTracking_security from "../timeTracking_security.js";
import type * as unsubscribe from "../unsubscribe.js";
import type * as userProfiles from "../userProfiles.js";
import type * as users from "../users.js";
import type * as userSettings from "../userSettings.js";
import type * as validators_index from "../validators/index.js";
import type * as watchers from "../watchers.js";
import type * as webhooks from "../webhooks.js";
import type * as workspaces from "../workspaces.js";
import type * as yjs from "../yjs.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  analytics: typeof analytics;
  "api/issues": typeof api_issues;
  apiKeys: typeof apiKeys;
  attachments: typeof attachments;
  auditLogs: typeof auditLogs;
  auth: typeof auth;
  "auth.config": typeof auth_config;
  authWrapper: typeof authWrapper;
  automationRules: typeof automationRules;
  availability: typeof availability;
  bookingPages: typeof bookingPages;
  bookings: typeof bookings;
  calendarEvents: typeof calendarEvents;
  calendarEventsAttendance: typeof calendarEventsAttendance;
  crons: typeof crons;
  customFields: typeof customFields;
  customFunctions: typeof customFunctions;
  dashboard: typeof dashboard;
  documents: typeof documents;
  documents_project_access: typeof documents_project_access;
  documents_security: typeof documents_security;
  documentTemplates: typeof documentTemplates;
  documentVersions: typeof documentVersions;
  e2e: typeof e2e;
  "email/templates/index": typeof email_templates_index;
  "examples/index": typeof examples_index;
  export: typeof export_;
  files: typeof files;
  github: typeof github;
  googleCalendar: typeof googleCalendar;
  "googleOAuth.contract": typeof googleOAuth_contract;
  hourCompliance: typeof hourCompliance;
  http: typeof http;
  "internal/ai": typeof internal_ai;
  invites: typeof invites;
  issueLinks: typeof issueLinks;
  issues: typeof issues;
  issues_counts: typeof issues_counts;
  issues_date_range: typeof issues_date_range;
  "issues/helpers": typeof issues_helpers;
  issues_load_more: typeof issues_load_more;
  "issues/mutations": typeof issues_mutations;
  "issues/queries": typeof issues_queries;
  "issues/roadmap": typeof issues_roadmap;
  "issues/roadmap_pagination": typeof issues_roadmap_pagination;
  "issues/selectable": typeof issues_selectable;
  issues_smart_list: typeof issues_smart_list;
  "issues/soft_delete": typeof issues_soft_delete;
  labelGroups: typeof labelGroups;
  labels: typeof labels;
  "lib/apiAuth": typeof lib_apiAuth;
  "lib/batchHelpers": typeof lib_batchHelpers;
  "lib/boundedQueries": typeof lib_boundedQueries;
  "lib/constrainedValidators": typeof lib_constrainedValidators;
  "lib/encryption": typeof lib_encryption;
  "lib/errors": typeof lib_errors;
  "lib/issueHelpers": typeof lib_issueHelpers;
  "lib/logger": typeof lib_logger;
  "lib/migrations": typeof lib_migrations;
  "lib/pagination": typeof lib_pagination;
  "lib/permissions": typeof lib_permissions;
  "lib/queryLimits": typeof lib_queryLimits;
  "lib/rateLimiter": typeof lib_rateLimiter;
  "lib/relationships": typeof lib_relationships;
  "lib/softDeleteHelpers": typeof lib_softDeleteHelpers;
  "lib/ssrf": typeof lib_ssrf;
  "lib/teamAccess": typeof lib_teamAccess;
  "lib/timeUtils": typeof lib_timeUtils;
  "lib/userUtils": typeof lib_userUtils;
  meetingBot: typeof meetingBot;
  "mocks/issues": typeof mocks_issues;
  multiTenantIsolation: typeof multiTenantIsolation;
  notificationPreferences: typeof notificationPreferences;
  notifications: typeof notifications;
  oauthHealthCheck: typeof oauthHealthCheck;
  offlineSync: typeof offlineSync;
  onboarding: typeof onboarding;
  organizations: typeof organizations;
  OTPPasswordReset: typeof OTPPasswordReset;
  OTPVerification: typeof OTPVerification;
  presence: typeof presence;
  projectAccess: typeof projectAccess;
  projectMembers: typeof projectMembers;
  projects: typeof projects;
  projects_security: typeof projects_security;
  projectTemplates: typeof projectTemplates;
  prosemirror: typeof prosemirror;
  pumble: typeof pumble;
  purge: typeof purge;
  rateLimiting: typeof rateLimiting;
  rateLimits: typeof rateLimits;
  rbac: typeof rbac;
  reactions: typeof reactions;
  savedFilters: typeof savedFilters;
  serviceRotation: typeof serviceRotation;
  softDeleteCleanup: typeof softDeleteCleanup;
  sprints: typeof sprints;
  teams: typeof teams;
  templates: typeof templates;
  testConfig: typeof testConfig;
  testUtils: typeof testUtils;
  timeTracking: typeof timeTracking;
  timeTracking_security: typeof timeTracking_security;
  unsubscribe: typeof unsubscribe;
  userProfiles: typeof userProfiles;
  users: typeof users;
  userSettings: typeof userSettings;
  "validators/index": typeof validators_index;
  watchers: typeof watchers;
  webhooks: typeof webhooks;
  workspaces: typeof workspaces;
  yjs: typeof yjs;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
